print "hola"
print "aleluya aleluya por eso hay que cantar aleluya"
print "hola"
print "aleluya aleluya por eso hay que cantar aleluya"
print "hola"
print "aleluya aleluya por eso hay que cantar aleluya"
print "hola"
print "aleluya aleluya por eso hay que cantar aleluya"
